spring:
  application:
    name: recruitment

  datasource:
    url: jdbc:hsqldb:mem:fpl_recruitment;DB_CLOSE_ON_EXIT=TRUE
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  context-path: /api
  
logging:
  level:
    com.test.recruitment=DEBUG